### ISSUE TITLE
Why to read enctoken data from a file in bypass.py?

### ISSUE THREAD

**Issue by k4976** [ecomsense/stock-brokers#1]
Why to write & read data to & trom file when we have enctoken generated in bypass.py > authenticate() & getenctoken()?

**Comment by pannet1** [comment]
i can read from token file from second run. if it is not modified on the same day, i will invalidate it and regenerate a new password.
never trust github or any developer (including me) to store credentials. also if i keep the credentials outside the project, i can reuse the credentials for another project.

**Comment by k4976** [comment]
> i can read from token file from second run. if it is not modified on the same day, i will invalidate it and regenerate a new password. never trust github or any developer (including me) to store credentials. also if i keep the credentials outside the project, i can reuse the credentials for another project.


But you are not reading data from file, first it's generating new token then saving it in file then reading it from file which i think don't make any sense or code is not correct for the thing you want to implement. I think read data from file should be used in project in which it's going to be used not in this project OR if it's then correct the code
